# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 09:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=20)),
                ('body', ckeditor.fields.RichTextField(verbose_name=b'Content')),
                ('time', models.DateTimeField()),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cats', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IndexContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name=b'Content')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Catalog'),
        ),
    ]
