# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 09:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_aboutindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
