# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_inspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgpost',
            name='website',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
